# Generated by Django 4.1.2 on 2022-12-01 13:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_rename_avater_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('thumbnails', models.ImageField(upload_to='thumbnails')),
                ('date', models.DateField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('globalnews', models.BooleanField(default=False)),
                ('latestnews', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FlashNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_news', models.CharField(blank=True, max_length=500, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.profile')),
            ],
        ),
    ]
